import { useEffect, useState } from 'react';
import {
  ArrowRight, BriefcaseBusiness, Check, ChevronRight, CircleHelp, FileText,
  Handshake, Menu, MessageCircle, Moon, Send, Sparkles, Sun, Target, UsersRound, X
} from 'lucide-react';

const plans = [
  { slug: 'starter', name: 'Starter Strategy', upfront: '$500', fee: '14%', audience: 'Early-career and focused searches', features: ['ATS-ready master résumé', 'Search strategy intake', 'Up to 50 managed applications', 'Application tracker', 'Interview coordination support'] },
  { slug: 'professional', name: 'Professional Core', upfront: '$1,000', fee: '12%', audience: 'Professionals building search momentum', popular: true, features: ['Everything in Starter', 'Up to 150 tailored applications', 'LinkedIn profile optimization', 'Two cover-letter variants', 'Interview preparation session'] },
  { slug: 'elite', name: 'Elite Search Partner', upfront: '$1,800', fee: '10%', audience: 'Senior and specialist technical searches', features: ['Everything in Professional', 'Up to 300 tailored applications', 'Dedicated search coordinator', 'Recruiter-message coordination', 'Mock behavioral interview'] },
  { slug: 'executive', name: 'Executive Concierge', upfront: '$3,000', fee: '10%', audience: 'Directors, VPs, and executive searches', features: ['Everything in Elite', '90-day high-touch scope', 'Multi-channel role research', 'Hiring-manager outreach support', 'Offer and contract strategy'] },
];

const services = [
  ['Career positioning', 'Turn real work into a clear, measurable professional story.', 'Resume rebuild, LinkedIn positioning, ATS alignment, target-role clarity.'],
  ['Managed search', 'Keep a thoughtful job search moving while you focus on work and interviews.', 'Role sourcing, tailored applications, tracker visibility, search coordination.'],
  ['Interview readiness', 'Prepare for the conversations that materially change your options.', 'Behavioral preparation, system-design practice, feedback and follow-up strategy.'],
  ['Offer strategy', 'Evaluate the whole offer, then negotiate from informed confidence.', 'Compensation context, counter-offer planning, transition support.'],
];

function useRoute() {
  const [path, setPath] = useState(window.location.pathname || '/');
  useEffect(() => { const onPop = () => setPath(window.location.pathname || '/'); window.addEventListener('popstate', onPop); return () => window.removeEventListener('popstate', onPop); }, []);
  const go = (to) => { window.history.pushState({}, '', to); setPath(to); window.scrollTo({ top: 0, behavior: 'auto' }); };
  return [path, go];
}

function App() {
  const [path, go] = useRoute();
  const [dark, setDark] = useState(false);
  const [menu, setMenu] = useState(false);
  const [chatOpen, setChatOpen] = useState(false);
  const [chatReply, setChatReply] = useState('');
  const navigate = (to) => { setMenu(false); go(to); };
  const page = path === '/' ? <Home go={navigate} />
    : path === '/candidates' ? <CandidateHub go={navigate} />
    : path === '/candidates/services' ? <ServicesPage go={navigate} />
    : path === '/candidates/plans' ? <PlansPage go={navigate} />
    : path === '/hiring-teams' ? <HiringTeams go={navigate} />
    : path === '/contact' ? <ContactPage go={navigate} />
    : path === '/about' ? <AboutPage go={navigate} />
    : path === '/insights' ? <InsightsPage go={navigate} />
    : <NotFound go={navigate} />;

  return <main className={dark ? 'dark app-shell' : 'app-shell'}>
    <div className="announcement"><Sparkles size={14}/> Hyrzilla is building a more deliberate hiring experience <button onClick={() => navigate('/contact')}>Talk to us <ArrowRight size={13}/></button></div>
    <Header go={navigate} path={path} menu={menu} setMenu={setMenu} dark={dark} setDark={setDark}/>
    {page}
    <Footer go={navigate}/>
    <button className="back-top" onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })} aria-label="Back to top">↑</button>
    <div className="chat">{chatOpen && <div className="chat-panel"><div><span>H</span><b>Hyrzilla guide</b><button onClick={() => setChatOpen(false)}><X size={15}/></button></div><p>Where would you like to start?</p><button onClick={() => setChatReply('Candidate programs combine career positioning, managed search support, interview readiness, and offer strategy.')}>Candidate support</button><button onClick={() => setChatReply('Our employer workflow is being shaped around your hiring context. Leave your details and we will follow up personally.')}>Hiring teams</button>{chatReply && <small>{chatReply}</small>}</div>}<button className="chat-launch" onClick={() => setChatOpen(!chatOpen)}><MessageCircle size={19}/><span>Ask Hyrzilla</span></button></div>
  </main>;
}

function Header({ go, path, menu, setMenu, dark, setDark }) {
  const nav = [['Candidates', '/candidates'], ['Candidate Plans', '/candidates/plans'], ['Hiring Teams', '/hiring-teams'], ['Insights', '/insights']];
  return <nav className="nav route-nav"><button className="brand" onClick={() => go('/')}><span>H</span>Hyrzilla</button><div className="navlinks">{nav.map(([label, to]) => <button className={path === to ? 'current' : ''} key={to} onClick={() => go(to)}>{label}</button>)}</div><button className="theme-toggle" onClick={() => setDark(!dark)} aria-label="Toggle color mode">{dark ? <Sun size={16}/> : <Moon size={16}/>}</button><button className="nav-cta" onClick={() => go('/contact')}>Contact us <ArrowRight size={15}/></button><button className="menu" onClick={() => setMenu(!menu)}>{menu ? <X/> : <Menu/>}</button>{menu && <div className="mobile-menu">{nav.map(([label, to]) => <button key={to} onClick={() => go(to)}>{label}</button>)}<button onClick={() => go('/contact')}>Contact us</button></div>}</nav>
}

function Home({ go }) { return <>
  <section className="hero route-hero"><div className="grid-lines"/><div className="hero-copy"><p className="eyebrow"><span/> Career strategy for ambitious technologists</p><h1>Your next role<br/>should change <em>everything.</em></h1><p className="lede">Hyrzilla helps people move through job search with clarity—and helps hiring teams meet candidates with more intent behind every introduction.</p><div className="hero-actions"><button className="button primary" onClick={() => go('/candidates')}>Explore candidate support <ArrowRight size={18}/></button><button className="watch" onClick={() => go('/hiring-teams')}><BriefcaseBusiness size={19}/> I’m hiring a team</button></div><div className="trust"><div className="faces"><i>AM</i><i>RJ</i><i>SK</i><i>+</i></div><span>Human-led support for high-stakes<br/><strong>career and hiring decisions</strong></span></div></div><div className="hero-art"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="profile-card glass"><div className="profile-top"><span className="avatar">A</span><span><b>Arjun Mehta</b><small>Platform Engineer</small></span><b className="progress">82%</b></div><div className="progress-line"><i/></div><div className="skill-row"><span>Career narrative</span><b>Strong</b></div><div className="skill-row"><span>Interview readiness</span><b className="warm">Building</b></div></div><div className="offer-card glass"><small>OFFER MOMENTUM</small><div><b>3</b><span>active<br/>conversations</span></div><div className="tiny-bars"><i/><i/><i/><i/></div></div><div className="signal-card"><span>✦</span><div><small>YOUR SIGNAL IS RISING</small><b>Ready for the right room.</b></div></div></div></section>
  <section className="route-choice section"><div className="section-label">TWO DISTINCT SERVICES <span>01</span></div><div className="route-choice-grid"><article><span className="choice-number">01</span><p className="eyebrow"><span/> For professionals</p><h2>Build a job search with more <em>direction.</em></h2><p>Positioning, managed applications, interview preparation, and offer strategy—scoped around the stage of your career.</p><button className="text-link" onClick={() => go('/candidates')}>Explore candidate support <ArrowRight size={17}/></button></article><article><span className="choice-number">02</span><p className="eyebrow"><span/> For hiring teams</p><h2>Make every shortlist more <em>considered.</em></h2><p>Tell us about the role and team. We will shape the right recruitment conversation around your priorities.</p><button className="text-link" onClick={() => go('/hiring-teams')}>Explore hiring support <ArrowRight size={17}/></button></article></div></section>
  <section className="proof"><p>NOT A JOB BOARD. A BETTER WAY FORWARD.</p><div><strong>1:1</strong><span>human support<br/>per engagement</span></div><div><strong>4</strong><span>candidate program<br/>levels in USD</span></div><div><strong>0</strong><span>fake interview<br/>guarantees</span></div></section>
</> }

function CandidateHub({ go }) { return <PageHero eyebrow="FOR CANDIDATES" title={<>A job search that feels <em>like yours.</em></>} text="Hyrzilla is for professionals who want more than a résumé edit or an application bot. We bring the full search into one clear, human-led system." cta="Explore services" onCta={() => go('/candidates/services')} aside={<StepList/>}><section className="section"><div className="section-label">WHAT WE WORK ON <span>01</span></div><ServiceCards go={go}/></section></PageHero> }
function ServicesPage({ go }) { return <PageHero eyebrow="CANDIDATE SERVICES" title={<>The work behind a <em>stronger yes.</em></>} text="Choose help where it matters most, or combine it into a managed career search. Every engagement starts with your actual context—not a template." cta="See candidate plans" onCta={() => go('/candidates/plans')}><section className="section service-page"><div className="section-label">FOUR CONNECTED SERVICES <span>02</span></div><ServiceCards detailed/><section className="callout"><div><p className="eyebrow"><span/> Built around your goals</p><h3>No auto-apply spray. No generic AI copy.</h3><p>We only describe and deliver work the team can control: defined materials, transparent application activity, and practical search coordination.</p></div><button className="button primary" onClick={() => go('/contact')}>Talk through your search <ArrowRight size={16}/></button></section></section></PageHero> }

function PlansPage({ go }) { const [selected, setSelected] = useState(1); const [salary, setSalary] = useState(140000); const current = plans[selected]; return <PageHero eyebrow="CANDIDATE PLANS" title={<>Clear scope. <em>Real support.</em></>} text="All prices are in USD. Each program has an upfront investment plus a success fee triggered only after you start a new role; exact terms belong in the signed agreement." cta="Contact Hyrzilla" onCta={() => go('/contact')}><section className="section plans-page"><div className="section-label">FIND YOUR LEVEL <span>03</span></div><div className="price-grid multi-page-prices">{plans.map((plan, index) => <article key={plan.slug} className={selected === index ? 'chosen' : ''}>{plan.popular && <span className="popular">MOST CHOSEN</span>}<span className="tier">PROGRAM 0{index + 1}</span><h3>{plan.name}</h3><p>{plan.audience}</p><div className="price"><b>{plan.upfront}</b><span>upfront investment</span><small>+ {plan.fee} after job start</small></div><ul>{plan.features.map(feature => <li key={feature}><Check size={14}/>{feature}</li>)}</ul><button onClick={() => setSelected(index)}>{selected === index ? 'Selected program' : 'Select program'} <ArrowRight size={15}/></button></article>)}</div><div className="fee-tool"><div className="fee-copy"><span className="calc-icon">$</span><h3>Estimate the success fee.</h3><p>This calculator is an estimate only. The final trigger, salary basis, and payment timing must be stated in the service agreement.</p></div><div className="calculator"><div className="salary-value"><span>Target annual salary (USD)</span><b>${salary.toLocaleString()}</b></div><input type="range" min="60000" max="280000" step="5000" value={salary} onChange={(event) => setSalary(Number(event.target.value))}/><div className="calc-result"><span>{current.name}<br/><small>{current.fee} success fee</small></span><strong>${Math.round(salary * Number.parseInt(current.fee) / 100).toLocaleString()}</strong></div></div></div><div className="comparison compact-comparison"><h3>What a good agreement should make clear</h3><ul><li><Check size={15}/> What Hyrzilla will deliver and the application scope</li><li><Check size={15}/> What the candidate remains responsible for</li><li><Check size={15}/> Success-fee trigger and salary calculation</li><li><Check size={15}/> Payment timing and privacy expectations</li></ul></div></section></PageHero> }

function HiringTeams({ go }) { return <PageHero eyebrow="FOR HIRING TEAMS" title={<>Recruitment with more <em>context.</em></>} text="Hyrzilla’s employer experience is being shaped as a dedicated product—not a candidate page with a different headline. We are collecting the company-side requirements before locking its service model." cta="Start a hiring conversation" onCta={() => go('/contact')} aside={<CompanyBoard/>}><section className="section"><div className="section-label">THE EMPLOYER FLOW <span>01</span></div><div className="process-grid">{[['01','Understand the brief','Role, team, stack, seniority, hiring timeline, and what a great hire changes.'],['02','Confirm the partnership','Agree on scope and recruitment terms before candidate information is shared.'],['03','Present aligned talent','Share relevant profiles, coordinate conversations, and keep the process moving.'],['04','Support the start','Complete placement terms after the candidate joins your team.']].map(([number,title,body]) => <article key={number}><span>{number}</span><h3>{title}</h3><p>{body}</p></article>)}</div><p className="page-note">Detailed employer services, pricing, terms, and intake workflow will be added after the company-side reference and operating model are approved.</p></section></PageHero> }

function ContactPage({ go }) { const [kind, setKind] = useState('candidate'); const [done, setDone] = useState(false); return <PageHero eyebrow="CONTACT HYRZILLA" title={<>Start with the right <em>conversation.</em></>} text="Share enough context for a useful human follow-up. The form is a Phase 1 prototype: it confirms the experience locally but does not send data until the CRM integration phase."><section className="section contact-page"><div className="contact-layout"><div><h2>{kind === 'candidate' ? 'Career conversation' : 'Hiring conversation'}</h2><p>{kind === 'candidate' ? 'Tell us what you are aiming for and where the search feels difficult.' : 'Tell us who you need, what they will own, and when the team needs them.'}</p><div className="toggle"><button className={kind === 'candidate' ? 'selected' : ''} onClick={() => {setKind('candidate');setDone(false)}}>Career support</button><button className={kind === 'company' ? 'selected' : ''} onClick={() => {setKind('company');setDone(false)}}>Hiring support</button></div></div><ContactForm kind={kind} done={done} setDone={setDone} go={go}/></div></section></PageHero> }
function AboutPage({ go }) { return <PageHero eyebrow="ABOUT HYRZILLA" title={<>A calmer way to make a <em>major move.</em></>} text="Hyrzilla is being designed around a simple belief: people make better career and hiring decisions when the process is clear, human, and built for the actual stakes involved." cta="Contact us" onCta={() => go('/contact')}><section className="section"><div className="process-grid"><article><span>01</span><h3>Clarity</h3><p>Specific scope, visible work, and plain language at every stage.</p></article><article><span>02</span><h3>Agency</h3><p>Candidates and teams retain control of their own decisions and information.</p></article><article><span>03</span><h3>Care</h3><p>Ambitious work deserves human attention—not a generic automated funnel.</p></article></div></section></PageHero> }
function InsightsPage({ go }) { return <PageHero eyebrow="INSIGHTS" title={<>Useful context for the <em>next move.</em></>} text="A focused resource hub is coming next. It will explain the job-search process, transparent reverse recruiting, candidate preparation, and thoughtful technical hiring." cta="See candidate services" onCta={() => go('/candidates/services')}><section className="section insight-grid">{[['Reverse recruiting, explained','How a human-led managed search differs from auto-apply volume.'],['How to assess a candidate plan','The commitments worth comparing before you sign a service agreement.'],['Better technical hiring briefs','The context a recruitment partner needs before presenting candidate profiles.']].map(([title,body]) => <article key={title}><span>COMING SOON</span><h3>{title}</h3><p>{body}</p><button onClick={() => go('/contact')}>Ask Hyrzilla <ChevronRight size={16}/></button></article>)}</section></PageHero> }

function PageHero({ eyebrow, title, text, cta, onCta, aside, children }) { return <><section className="page-hero"><div className="page-hero-copy"><p className="eyebrow"><span/>{eyebrow}</p><h1>{title}</h1><p>{text}</p>{cta && <button className="button primary" onClick={onCta}>{cta}<ArrowRight size={17}/></button>}</div>{aside && <aside>{aside}</aside>}</section>{children}</> }
function ServiceCards({ detailed, go }) { return <div className={detailed ? 'service-card-grid detailed' : 'service-card-grid'}>{services.map(([title,short,detail], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{detailed ? detail : short}</p>{go && <button onClick={() => go('/contact')}>Talk to us <ChevronRight size={16}/></button>}</article>)}</div> }
function StepList(){ return <div className="mini-panel"><span>YOUR SEARCH, SIMPLIFIED</span><b>1. Position</b><b>2. Search</b><b>3. Interview</b><b>4. Decide</b></div> }
function CompanyBoard(){ return <div className="mini-panel company-mini"><span>HIRING CONTEXT</span><b>Team and role brief</b><b>Shared service scope</b><b>Relevant candidate profiles</b><b>Clear handoff and start</b></div> }
function ContactForm({ kind, done, setDone, go }) { if(done) return <div className="contact-form success-state"><span><Check size={24}/></span><h3>Thank you.</h3><p>Your Phase 1 contact experience is complete. In Phase 2, this will create a CRM record, send confirmation, and offer calendar booking.</p><button onClick={() => go('/')}>Return home</button></div>; return <form className="contact-form" onSubmit={(event) => {event.preventDefault();setDone(true)}}><div className="form-grid"><label>Full name<input required placeholder="Your name"/></label><label>{kind === 'candidate' ? 'Email address' : 'Work email'}<input required type="email" placeholder="name@email.com"/></label><label>{kind === 'candidate' ? 'Current role' : 'Company name'}<input required placeholder={kind === 'candidate' ? 'e.g. Senior Backend Engineer' : 'Your company'}/></label><label>{kind === 'candidate' ? 'Experience level' : 'Roles to hire'}<input required placeholder={kind === 'candidate' ? 'e.g. 4–7 years' : 'e.g. DevOps, Engineering Lead'}/></label></div><label className="wide-label">{kind === 'candidate' ? 'What would make your next move meaningful?' : 'What would make this hire a success?'}<textarea rows="4" required placeholder="Share the context, timeline, and goals…"/></label><button className="button primary full" type="submit">Send inquiry <Send size={16}/></button><small>This Phase 1 prototype does not submit data externally.</small></form> }
function Footer({ go }) { return <footer><button className="brand" onClick={() => go('/')}><span>H</span>Hyrzilla</button><p>Career momentum, engineered.</p><div><button onClick={() => go('/about')}>About</button><button onClick={() => go('/insights')}>Insights</button><button onClick={() => go('/contact')}>Contact</button></div></footer> }
function NotFound({ go }) { return <section className="not-found"><p className="eyebrow"><span/> 404</p><h1>This page is not here yet.</h1><button className="button primary" onClick={() => go('/')}>Back home <ArrowRight size={16}/></button></section> }

export default App;
